//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/#Project/InputSystem/MicInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MicInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MicInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MicInput"",
    ""maps"": [
        {
            ""name"": ""Mic"",
            ""id"": ""adc5dfd3-ae7b-4a5a-a419-606ac7a695c2"",
            ""actions"": [
                {
                    ""name"": ""ShowHide"",
                    ""type"": ""Button"",
                    ""id"": ""c4c52593-45c0-456c-b1c9-60e1ffac160e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""71bee40f-889a-4f75-a843-335d6cd2d95d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowHide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Mic
        m_Mic = asset.FindActionMap("Mic", throwIfNotFound: true);
        m_Mic_ShowHide = m_Mic.FindAction("ShowHide", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mic
    private readonly InputActionMap m_Mic;
    private List<IMicActions> m_MicActionsCallbackInterfaces = new List<IMicActions>();
    private readonly InputAction m_Mic_ShowHide;
    public struct MicActions
    {
        private @MicInput m_Wrapper;
        public MicActions(@MicInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShowHide => m_Wrapper.m_Mic_ShowHide;
        public InputActionMap Get() { return m_Wrapper.m_Mic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MicActions set) { return set.Get(); }
        public void AddCallbacks(IMicActions instance)
        {
            if (instance == null || m_Wrapper.m_MicActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MicActionsCallbackInterfaces.Add(instance);
            @ShowHide.started += instance.OnShowHide;
            @ShowHide.performed += instance.OnShowHide;
            @ShowHide.canceled += instance.OnShowHide;
        }

        private void UnregisterCallbacks(IMicActions instance)
        {
            @ShowHide.started -= instance.OnShowHide;
            @ShowHide.performed -= instance.OnShowHide;
            @ShowHide.canceled -= instance.OnShowHide;
        }

        public void RemoveCallbacks(IMicActions instance)
        {
            if (m_Wrapper.m_MicActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMicActions instance)
        {
            foreach (var item in m_Wrapper.m_MicActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MicActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MicActions @Mic => new MicActions(this);
    public interface IMicActions
    {
        void OnShowHide(InputAction.CallbackContext context);
    }
}
